import { FunctionComponent } from "react";
import ActionAnchor from "../ui/atomic/anchor/ActionAnchor";
import Dot from "../ui/atomic/badge/dot/Dot";
import Notification from "../ui/atomic/badge/notification/Notification";
import Pill from "../ui/atomic/badge/pill/Pill";
import ActionButton from "../ui/atomic/button/ActionButton";
import CheckboxLabel from "../ui/atomic/checkbox/CheckboxLabel";
import Dropdown from "../ui/atomic/dropdown/Dropdown";
import Image from "../ui/atomic/image/Image";
import ActionLink from "../ui/atomic/link/ActionLink";
import Text from "../ui/atomic/text/Text";
import Title from "../ui/atomic/title/Title";
import Action from "../ui/components/action/Action";
import Breadcrumb from "../ui/components/breadcrumb/Breadcrumb";
import ButtonDropdown from "../ui/components/button-dropdown/ButtonDropdown";
import Card from "../ui/components/card/Card";
import Carousel from "../ui/components/carousel/Carousel";
import Loading from "../ui/components/loading/Loading";
import Message from "../ui/components/message/Message";
import Modal from "../ui/components/modal/modal/Modal";
import Pagination from "../ui/components/pagination/Pagination";
import Snackbar from "../ui/components/snackbar/Snackbar";
import Story from "../ui/components/story/Story";
import Tabs from "../ui/components/tabs/Tabs";

const UIMapper = new Map<string, FunctionComponent<any>>();
UIMapper.set("anchor", ActionAnchor);
UIMapper.set("link", ActionLink);
UIMapper.set("button", ActionButton);
UIMapper.set("dot", Dot);
UIMapper.set("notification", Notification);
UIMapper.set("pill", Pill);
UIMapper.set("checkbox", CheckboxLabel);
UIMapper.set("dropdown", Dropdown);
UIMapper.set("image", Image);
UIMapper.set("text", Text);
UIMapper.set("title", Title);
UIMapper.set("action", Action);
UIMapper.set("breadcrumb", Breadcrumb);
UIMapper.set("button-dropdown", ButtonDropdown);
UIMapper.set("card", Card);
UIMapper.set("carousel", Carousel);
UIMapper.set("loading", Loading);
UIMapper.set("message", Message);
UIMapper.set("modal", Modal);
UIMapper.set("pagination", Pagination);
UIMapper.set("snackbar", Snackbar);
UIMapper.set("story", Story);
UIMapper.set("tabs", Tabs);

const getComponent = (uiType: string, props: any) => {
  const Component = UIMapper.get(uiType);
  if (Component) return Component(props);
  return <p>Component with uiType {uiType} does not exist.</p>;
};
export default getComponent;
